k8sp/sextant

config/dhcp_conf.go
config/dhcp_conf_test.go
config/etcd_test.go

Fixes https://github.com/k8sp/auto-install/issues/35

Both hostname and MAC address are lower cased.

---

bootstrapper/cmd/cmd.go
bootstrapper/cmd/cmd_test.go
bootstrapper/skydns/skydns.go
bootstrapper/skydns/skydns_test.go

基于 https://github.com/k8sp/auto-install/pull/61 ，修改 https://github.com/k8sp/auto-install/pull/58

Bootstrapper skydns yi

---

cloud-config-server/server.go
cloud-config-server/template/template.go
cloud-config-server/template/template_test.go

format code

---

bootstrapper/nginx/nginx_conf.go
bootstrapper/nginx/nginx_conf_test.go
bootstrapper/skydns/skydns.go
bootstrapper/skydns/skydns_test.go
config/etcd.go
config/etcd_test.go

Fix https://github.com/k8sp/auto-install/issues/80
Fix https://github.com/k8sp/auto-install/issues/79
Fix https://github.com/k8sp/auto-install/issues/78

Add Test service unit

---

bootstrapper/cmd/cmd.go
bootstrapper/nginx/nginx_conf_test.go
bootstrapper/skydns/skydns_test.go
cloud-config-server/cache/cache.go
cloud-config-server/cache/cache_test.go
config/etcd_test.go

因为我的 PR #81 修改了 config/config.go 里 ExampleYAML 里的配置（用Vagrant VM的默认subnet，而不再是Docker的默认subnet），但是我没有修改现有的nginx_conf.go 和 skydns_conf.go，所以我 merge #81 之后，master branch的TravisCI test fail了。这个PR就是紧急修改这个test fail的。

Fixes things left behind PR #81

---

bootstrapper/vmtest/run

Fixes https://github.com/k8sp/auto-install/issues/90

Make vmtest/run clean up well

---

cloud-config-server/template/cloud-config.template

fix https://github.com/k8sp/auto-install/issues/94

only master config flannel net

---

cloud-config-server/cache/cache.go
cloud-config-server/server.go
cloud-config-server/server_test.go

Fixes https://github.com/k8sp/auto-install/issues/104

Fix issue 104 in cache.go

---

cloud-config-server/template/cloud-config.template
cloud-config-server/template/template.go

Fix https://github.com/k8sp/auto-install/issues/98

Get bootstrapper IP from config in cloud config

---

bootstrapper/coreos/coreos_test.go
cloud-config-server/cache/cache.go
cloud-config-server/server.go
cloud-config-server/server_test.go

Add static file handler

---

bsroot/.gitignore
bsroot/README.md
bsroot/bsroot/gen-ca-and-bootstrapper-certs.bash
bsroot/registry.Dockerfile
bsroot/vm-cluster/Vagrantfile

Fixes https://github.com/k8sp/k8s-tensorflow/issues/9

Enable TLS with Docker registry and test it in a VM cluster.

---

bootstrapper/skydns/skydns_test.go
cloud-config-server/build.sh
cloud-config-server/certgen/certgen.go
cloud-config-server/template/cloud-config.template
cloud-config-server/template/template.go
cloud-config-server/template/template_test.go
cloud-config-server/template/unisound-ailab/build_config.yml
config/config.go
config/etcd.go
config/etcd_test.go
config/master.go

1. 将原有IP部分修改为hostname的方式
1. 修改了cloud-config.template中的部分问题
1. fixed #127

Fixedip2hostname

---

cloud-config-server/server.go

if ca-crt or ca-key is not ready, server exit.

---

bootstrapper/dhcp/dhcp_conf.go
bootstrapper/dhcp/dhcp_conf_test.go
bootstrapper/skydns/skydns_test.go
cloud-config-server/template/template.go
cloud-config-server/template/template_test.go
cloud-config-server/template/unisound-ailab/build_config.yml
config/config.go
config/etcd.go
config/etcd_test.go
config/master.go
config/master_test.go

Delete fixedIP config in cluster-desc.yml

---

README.md
bsroot.sh
cloud-config-server/template/cloud-config.template

add registry tls

---

README.md
bsroot.sh
cloud-config-server/install.sh
cloud-config-server/template/cloud-config.template

Fixes https://github.com/k8sp/sextant/issues/171
For more information about this PR, please refer to above issue.

Make wget curl silent

---

bsroot.sh
cloud-config-server/install.sh

Fix https://github.com/k8sp/sextant/issues/176
Fix https://github.com/k8sp/sextant/issues/182
Obtain the MAC address of the default interface

Fix MAC address

---

bsroot.sh
cloud-config-server/template/cloud-config.template
start.sh

add 8081 port

---

bsroot.sh
cloud-config-server/template/cloud-config.template
cloud-config-server/template/template.go
cloud-config-server/template/unisound-ailab/build_config.yml
config/config.go
start.sh

* modprobe rbd for ceph rbd on k8s usage
* make all hyperkube, pause, flannel image version configurable

make k8s version configurable

---

bsroot.sh

修复build bootstrapper dockefile路径导致的异常

---

bsroot.sh

Fix the problem mentioned in https://github.com/k8sp/sextant/pull/189/files#r79850627

Download CoreOS version.txt and keep current a symbolic link

---

bsroot.sh
start.sh

Use double quotas instead of single quotas

---

addons/README.md

update addons readme

---

bsroot.sh

将pxe安装等待时间修改为0,无需等待直接安装

---

bsroot.sh

Fix https://github.com/k8sp/sextant/issues/229

修改无法找到脚本bug

---

docker/Dockerfile

修复issue 224

---

bsroot.sh
docker/entrypoint.sh

fix issue 238

---

cloud-config-server/template/cloud-config.template

修复issue 231

---

bsroot.sh
start_bootstrapper_container.sh

修改路径错误和镜像名称截取错误
Fix https://github.com/k8sp/sextant/issues/230

修改路径错误和镜像名称截取错误

---

vm-cluster/README.md
vm-cluster/Vagrantfile
vm-cluster/cluster-desc.yml.template
vm-cluster/prepare_install_bootstrapper.sh
vm-cluster/provision_bootstrapper_vm.sh

vm cluster最新代码

---

start_bootstrapper_container.sh

fix duplicate hosts

---

addons/addons.go
addons/template/dnsmasq.conf.template
bsroot.sh
clusterdesc/config.go
docker/entrypoint.sh

Fixes https://github.com/k8sp/sextant/issues/213
auto generate dnsmasq.conf according to cluster-desc

gen dnsmasq.conf from cluster-desc

---

vm-cluster/prepare_install_bootstrapper.sh

修复ssh免密码bug

---

bsroot.sh

fix bug 284

---

bsroot.sh

Remove generate_dnsmasq_config function

---

docker/entrypoint.sh

Run dnsmasq after generated dnsmasq config

---

vm-cluster/prepare_install_bootstrapper.sh

修复找不到目标文件夹vm-keys bug

---

bsroot.sh

Check sextant dir

---

bsroot.sh

Exit when build bootsrapper image failed

---

vm-cluster/Vagrantfile
vm-cluster/cluster-desc.yml.template

vm-cluster 添加ceph支持，目前vm支持sata硬盘不好用，暂时采用ide的硬盘

vm-cluster 添加ceph支持

---

bsroot.sh
docker/Dockerfile

Fix build registry

---

clusterdesc/etcd.go
clusterdesc/etcd_test.go
clusterdesc/master.go

Restructure duplicate code in clusterdesc package 

---

bsroot.sh
docker/.gitignore

Fix can not find registry binary file

---

cloud-config-server/template/cloud-config.template
vm-cluster/Vagrantfile
vm-cluster/provision_bootstrapper_vm.sh

Config DNS namesearch and search with startup bootstrapper

---

vm-cluster/Vagrantfile

修复worker节点无法安装coreos问题

---

install-ceph/README.md

Add instructions of using ceph in k8s pod.

add ceph readme for using rbd in k8s

---

README.md

Fix go get sextant dependent packages

---

bsroot.sh

Fixes https://github.com/k8sp/sextant/issues/342

Use -N in addition to -c with wget

---

cloud-config-server/template/template.go
clusterdesc/config.go

Fix osd not install due to a template parse issue

fix osd not install

---

bsroot.sh

Fix not copy binaries after build in docker

fix_not_cp_binaries

---

bsroot.sh
cloud-config-server/template/cloud-config.template
install-ceph/install-mon.sh
vm-cluster/cluster-desc.yml.template

fix flannel config bug and 347

---

bsroot.sh

Fixed #359 
Fixed #360 
Fixed #361

fix_359_360_361

---

start_bootstrapper_container.sh

Fix https://github.com/k8sp/sextant/issues/358

Fix a spell error

---

cloud-config-server/template/cloud-config.template
cloud-config-server/template/cluster-desc.sample.yaml
cloud-config-server/template/template.go
clusterdesc/config.go
vm-cluster/cluster-desc.yml.template

解决coreos可以配置是否更新系统

---

bsroot.sh
bsroot_lib.bash
bsroot_test.bats
testdata/example.yaml

这个PR是修复 Fixes https://github.com/k8sp/sextant/issues/239 的第一步。这一步里我只是
1. 把 check_prerequisites 从 bsroot.sh 挪到 bsroot_lib.bash 里
2.  增加 bsroot_test.bats 来测试 check_prerequisites 和 load_yaml （load_yaml 调用了 parse_yaml）
我希望一个比较小的PR更容易review。

Unit test check_prerequisites and parse/load_yaml in bsroot.sh

---

bsroot_centos.sh
bsroot_common.sh
start_bootstrapper_container.sh

bsroot_common.sh 大部分内容是 bsroot.sh 复制，review 的时候可以忽略
CentOS 相关的主要是 bsroot_centos.sh

Install CentOS via PXE

---

addons/addons.go
addons/template/ingress.template
bsroot.sh
cloud-config-server/template/cluster-desc.sample.yaml
clusterdesc/config.go
vm-cluster/cluster-desc.yml.template

Add ability to config bsroot.sh to generate ingress.yaml with "hostNetwork" configurations if add `ingress_hostnetwork: true` line in cluster-desc.yaml

Add config for ingress hostNetwork

---

addons/template/default-backend-svc.yaml
addons/template/default-backend.template
addons/template/ingress.template
cloud-config-server/template/cloud-config.template
cloud-config-server/template/cluster-desc.sample.yaml
scripts/common.sh
vm-cluster/cluster-desc.yml.template

Add default backend

---

scripts/centos.sh

Fix GPU directory

---

scripts/common.sh

Remove BLOCK comment

---

scripts/centos.sh

Fix #426 
Fix GPU download directory error， remove ‘nvidia_installers’ subdirectory

Remove check file exist before wget

---

scripts/centos.sh

Fix loading nvidia-uvm

---

bsroot.sh
cloud-config-server/template/cluster-desc.sample.yaml
scripts/common.sh
scripts/coreos.sh
vm-cluster/cluster-desc.yml.template

fix issue 433

---

scripts/centos.sh
scripts/common.sh
vm-cluster/cluster-desc.yml.template

Fixed #434 
install docker specify version for CentOS

install docker specify version for CentOS

---

cloud-config-server/template/cluster-desc.sample.yaml
scripts/centos.sh
vm-cluster/cluster-desc.yml.template

 fix issues 457

---

addons/addons.go
addons/template/dnsmasq.conf.template
cloud-config-server/clusterdesc/config.go
cloud-config-server/template/cluster-desc.sample.yaml

Add dnsmasq lease option in yaml config file

---

scripts/centos/post-process.sh

Remove ssh confirm on CentOS

---

bsroot.sh
scripts/centos.sh
scripts/centos/post-process.sh

to make the code of centos scripts clear
Fix #478

Refactor the code of centos scripts 

---

cloud-config-server/clusterdesc/config.go
cloud-config-server/server.go
cloud-config-server/template/template.go

Check MAC Address

---

bsroot.sh
scripts/common.sh
scripts/coreos.sh
scripts/coreos/install.sh

Refactor the code of coreos install script

---

scripts/common.sh

Recover the code mistakenly deleted in #493

Recover the code deleted in PR493

---

golang/template/templatefiles/cc-centos.template

Fix #500 
After=network.target

Add etcd.service dependence
