- bootstrapper/cmd/cmd.go
- bootstrapper/cmd/cmd_test.go
So we can do 
```
cmd.RunWithEnv([]string{"GOPATH=/tmp"}, "go", "get", "github.com/skynetservices/skydns")
```
to build SkyDNS and save into `/tmp/bin/skydns`.
> Add RunWithEnv and TryWithEnv

- cloud-config-server/cache/cache.go
- cloud-config-server/cache/cache_test.go
```
var (
c *cache.Cache
)
func main() {
c = cache.New(url, filename)
http.Handle("/", handler)
}
func handler(...) {
c.Get() // returns cache content and triggers update. No waiting.
}
```
> Add cache for cloud-config-server

- bootstrapper/vmtest/run
Fixes https://github.com/k8sp/auto-install/issues/92
这是一个临时性的应对。在vagrant发布1.8.6之后就不需要了。所以我在修改的源码里做了一个很长的注释说明。
目前在跑vmtest/run的时候，在使用CentOS guest的时候，会要求大家手工三次输入口令 "vagrant"。
我尝试了，用来测试 bootstrapper/dhcp 和 bootstrapper/nginx 都通过了。
> Temporary hacky solution to vagrant cannot ssh to CentOS guests

- cloud-config-server/server.go
- cloud-config-server/server_test.go
Fixes https://github.com/k8sp/auto-install/issues/77
为了unit test一个HTTP server，我把server的代码大幅度修改了，这样方便在一个goroutine里启动。
另外，对cloud-config-server的访问方式（URL）也修改成了？
```
http://<addr:port>/cloud-config/aa:bb:cc:dd:ee:ff
```
而不是以前的
```
http://<addr:port>/cloud-config/aa-bb-cc-dd-ee-ff.yml
```
> Add unit test for cloud-config-server

- bootstrapper/vmtest/run
Fixes https://github.com/k8sp/auto-install/issues/92
The problem reported in above issue is due to a bug in Vagrant 1.8.5.  I used to think that we cannot downgrade Vagrant from 1.8.5 to 1.8.4 to escape from this bug, but I was wrong -- the uninstallation of Vagrant on Mac OS X is described [here](http://stackoverflow.com/questions/34027853/uninstall-vagrant-on-mac) as:
```
rm -rf /opt/vagrant
rm -f /usr/bin/vagrant
```
Once we do that, we can download the right version of Vagrant https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4.dmg and install it.
So this PR just revert the previous change https://github.com/k8sp/auto-install/pull/96
> No more hacky tricks in vmtest/run

- cloud-config-server/server.go
原来的写法是
```
caCrt := *flag.String("ca-crt", "", "CA certificate file, in PEM format")
```
随后用`caCrt`当做`flag.Parse()`的flag value。
这样其实不行，因为caCrt的值在`flag.Parse()`之前和之后都是`""`，因为caCrt的值被`flag.String`赋了默认值。
> Fix a bug about flag parsing in cloud-config-server

- bsroot.sh
When the first time I ran bsroot.sh on my MacBook without gpg installed, the shell script didn't break the processing. So I add this function that checks if all the tools used are there, and exit if they aren't.
> Check availability of tools used by bsroot.sh

- Dockerfile
- bootstrapper/coreos/coreos.go
- bootstrapper/coreos/coreos_test.go
- bootstrapper/dhcp/dhcp.go
- bootstrapper/dhcp/dhcp_conf.go
- bootstrapper/dhcp/dhcp_conf_test.go
- bootstrapper/dhcp/dhcp_test.go
- bootstrapper/nginx/nginx.go
- bootstrapper/nginx/nginx_conf.go
- bootstrapper/nginx/nginx_conf_test.go
- bootstrapper/nginx/nginx_test.go
- bootstrapper/skydns/skydns.go
- bootstrapper/skydns/skydns_test.go
- cloud-config-server/README.md
- cloud-config-server/certgen/certgen.go
- cloud-config-server/server.go
- cloud-config-server/server_test.go
- cloud-config-server/template/cloud-config.template
- cloud-config-server/template/template.go
- cloud-config-server/template/template_test.go
- cloud-config-server/template/unisound-ailab/build_config.yml
- config/config.go
- doc/bootstrapper.md
fix #159 
1. 将cluster-dns变量统一放在cluster-desc中进行配置
1. 将原有package名为auto-install的地方都修改为sextant
1. 由于coreos版本stable和alpha版本号没有稳定的逻辑关系，去掉了coreos模块中关于version的测试
> add k8s cluster dns var in cluster-desc.yaml

- cloud-config-server/template/cloud-config.template
Fixes #163 
flanneld 依赖etcd2启动
Fixes #164 
始终使用early-docker来启动flannel，避免新版coreos使用rkt启动flannel带来的问题
> flannel always on early-docker

- bsroot.sh
上次提交registry tls pr时，忘了提交这部分的修改，需要指定registry证书所在位置
> update registry tls

- .gitignore
- bsroot.sh
- cloud-config-server/install.sh
Fixes https://github.com/k8sp/sextant/issues/177
Fixes https://github.com/k8sp/sextant/issues/175
Fixes https://github.com/k8sp/sextant/issues/173
I verified this change by running the changed `bsroot.sh` on my iMac -- **but not yet in vm-cluster or a real cluster**.  To run this script:
```
go get github.com/k8sp/sextant
cd /tmp
$GOPATH/src/github.com/k8sp/sextant/bsroot.sh $GOPATH/src/github.com/k8sp/sextant/cloud-config-server/template/unisound-ailab/build_config.yml
```
Above commands generates `/tmp/bsroot` and prints the following progress information:
```
$ ../sextant/bsroot.sh ../sextant/cloud-config-server/template/unisound-ailab/build_config.yml 
Using cluster-desc file /Users/yi/work/src/github.com/k8sp/vm-cluster/../sextant/cloud-config-server/template/unisound-ailab/build_conf …
```
> Polishing bsroot.sh

- bsroot.sh
因为k8s环境系统已经安装，ip已经固定分配，使用公司统一的dns。
需要在bsroot.sh注释掉需要的函数
check_prerequisites
#download_pxe_images
#generate_pxe_config
#generate_dnsmasq_config
generate_registry_config
prepare_cc_server_contents
download_k8s_images
我在generate_registry_config()函数添加了创建sextant/bsroot/config目录，如果目录存在就继续往下走，否则就创建。
> update create sextant/bsroot/config

- bsroot.sh
- start.sh
将bootstrapper镜像保存到bsroot目录，在start.sh的时候load进去，并运行bootstrapper
> 将bootstrapper镜像保存到bsroot目录

- start.sh
1，删除bootstrapper启动顺序导致的异常，bootstrapper启动后会调start.sh，不是start.sh起bootstrapper
2，删除/bsroot/html/static/cloud-configs/install.sh不必要的替换，bsroot.sh已经替换过这个变量
> 修复bootstrapper启动顺序逻辑错误

- bsroot.sh
It's a waste of time to download the 1.4 GB sized kubernetes.tar.gz for
just the kubelet and kubectl which are about 160 MB in total.
Resolves #206
> Remove unnecessary downloading

- docker/build.bash
Fixes https://github.com/k8sp/sextant/issues/242
为了让build.bash在任何操作系统执行时，都把cloud-config-server和addons编译成 linux_amd64 格式的可执行文件，我引入了cross-compilation。
如果执行 build.bash 的机器恰好就是 linux_amd64，那么生成的文件在 $GOPATH/bin；否则（cross-compilation生效）结果在 $GOPATH/bin/linux_amd64。
> Edit build.bash to make sure it can run on Linux or non-Linux systems

- docker/Dockerfile
- docker/build.bash
Fixes https://github.com/k8sp/sextant/issues/260
Fixes https://github.com/k8sp/sextant/issues/224 , which was not completely resolved by https://github.com/k8sp/sextant/pull/252
For a thorough experiment that support this change, please refer to https://github.com/wangkuiyi/build-statically-linked-go-programs
> Make sure to build fully statically-linked Go programs

- docker/Dockerfile
It seems that `docker/entrypoint.sh` does no longer run `docker push <basic-images>`; instead, `start_bootstrapper_container.sh` does so. So there is no need to install `docker` in `docker/Dockerfile`.
> No apk add docker in docker/Dockerfile

- bsroot.sh
@lipeng-unisound 开会时候提到：
- 目前的bsroot.sh输出./bsroot。但是 @lipeng-unisound 习惯把输出放到 /bsroot。所以每次 `mv ./bsroot /bsroot`之后，再次运行 bsroot.sh 时就会从头下载。
所以我做了这个修改：
- 让bsroot.sh有第二个可选参数，指定输出目录（bsroot）。如果不指定这个参数，则默认输出是 `$SEXTANT_DIR/bsroot`。
这样， @lipeng-unisound 就可以这样使用 bsroot.sh了：
```
$GOPATH/src/github.com/k8sp/sextant/bsroot.sh some-cluster-desc.yml /bsroot
```
在我自己的iMac上测试，可以正常生成 $SEXTANT_DIR/bsroot 目录：
```
cd ~
export SEXTANT_DIR=$GOPATH/src/github.com/k8sp/sextant
$SEXTANT_DIR/bsroot.sh \
$SEXTANT_DIR/cloud-config-server/template/unisound-ailab/build_config.yml 
```
> Let bsroot.sh can have the second parameter to specify bsroot directory

- .gitignore
- addons/addons.go
- addons/template/dnsmasq.conf.template
- bsroot.sh
- cloud-config-server/template/cloud-config.template
- clusterdesc/config.go
- docker/entrypoint.sh
- setup-kubectl.bash
- start_bootstrapper_container.sh
- vm-cluster/README.md
- vm-cluster/Vagrantfile
- vm-cluster/cluster-desc.yml.template
- vm-cluster/prepare_install_bootstrapper.sh
- vm-cluster/provision_bootstrapper_vm.sh
简化了kubectl的配置过程，做了如下修改:
* merge 了master的代码，可使用vm-cluster进行测试了。
* 在"笔记本上" 执行bsroot.sh 期间会将cluster-desc中kube-master-hostname,hyperkube-version信息写入setup-kubectl.bash中
* 在kubernetes client的机器上将setup-kubectl.bash 以scp的方式获取下来，脚本会根据系统类型下载对应kubectl的二进制文件并自动配置到集群的master节点。
* 将通过TLS认证的连接方式改为连接非认证的8080端口。
> Add setting up kubectl - Yancey

- addons/template/dnsmasq.conf.template
- cloud-config-server/template/unisound-ailab/build_config.yml
在 `dnsmasq.conf` 中添加 upstream DNS, 当解析 dnsmasq 无法处理的域名时， 通过 upstream DNS 解析
> Add upstream DNS

- addons/addons.go
- addons/template/dnsmasq.conf.template
- bsroot.sh
- cloud-config-server/template/unisound-ailab/build_config.yml
- clusterdesc/config.go
1. Dnsmasq config template will use cluster-desc "UpstreamNameServers" to setup upstream name servers.
2. bsroot.sh will check reqirements of command "make".
NOTE: lots of code formatting problems
> make dnsmasq upstream config from cluster-desc

- bsroot.sh
- docker/Dockerfile
- docker/entrypoint.sh
- start_bootstrapper_container.sh
Fixes https://github.com/k8sp/sextant/issues/236
Fixes https://github.com/k8sp/sextant/issues/314
Fixes https://github.com/k8sp/sextant/issues/123
> Use alpine instead of golang:alpine as the base image of boostrapper

- bsroot.sh
#401 
把cloud-init 相关依赖包下载后放到/bsroot/html/static/CentOS7/repo 目录下，使用createrepo创建本地yum源
> CentOS 7 制作本地cloud-init 源

- scripts/centos.sh
If we use `hostnamectl set-hostname` to set hostname, the hostname
is full length, mac address combined with domainname, but only the
mac address is expected. This issue is solved by writing the address
string to /etc/hostname directly.
> Fix set-hostname issue

- bsroot.sh
- scripts/centos.sh
* Fix #409 , Fix invoking generating rpm function
* Install cloud-init via kickstart
* Remove `ignoremissing` flag in kickstart configuration file
> Install cloud-init via kickstart

- bsroot.sh
- scripts/centos.sh
Fix #395 
在scripts/centos.sh中增加了一个函数download_centos_gpu_drivers()：
1.  下载指定版本号(scripts/centos.sh 183行)的nvidia gpu驱动到bsroot/html/static/CentOS7/gpu_drivers中
2. .创建一个驱动的安装脚本，保存到bsroot/html/static/CentOS7/gpu_drivers/build_centos_gpu_drivers.sh
集群安装驱动时，将bsroot/html/static/CentOS7/gpu_drivers目录（包含驱动和安装脚本）拷贝或http下载到集群节点上，cd gpu_drivers; sh build_centos_gpu_drivers.sh 完成安装
> WIP: Download and install nvidia gpu drivers on centos

- scripts/bsroot_lib.bash
- scripts/centos.sh
- start_bootstrapper_container.sh
fixes #390 
1. 使用私有源安装docker 、 etcd、flannel
2. start_bootstrapper_container.sh 中默认的 bsroot 不合理的问题。
3. 增加了一个支持解析 yaml 数组的方法 parse_yaml2 ，虽然支持了解析 yaml 中的数组，但仍有一些小问题： ssh-key 中存在空格，会被当做多个 value 存入数组
> Centos install docker etcd flannel

- doc/centos-design.md
描述下如何基于 CentOS 的 Kubernetes 集群及其附属组件和服务的自动安装与配置。
在实现的过程中，看如何能够尽量复用基于 CoreOS 安装配置的已有的脚本和功能模块，还需要讨论。
> CentOS design

- cloud-config-server/template/cloud-config.template
Fix #441 
在cloud-config.template 文件中，ceph-mon.service 和 ceph-osd.service 的地方，增加依赖关系： docker.service ，解决安装 ceph 的时候，docker.service 还没有启动起来，导致 ceph 安装失败的问题。
> fix 441: ceph-mon.service and ceph-osd.service  dependent on docker.service

- scripts/centos.sh
- scripts/common.sh
Fix #447 
so we can use overlay as the storage driver for docker,
replace the default one (devicemapper) on centos.
> Install anothor kernel for CentOS

- golang/template/cluster-desc.sample.yaml
- scripts/common/addons.sh
主要改动在两部分：
1. addons.sh 中路径写错了，应该没有 /golang  这个是一个 bug
2. sample 默认配置更新，这个不属于 bug 范畴：
* GPU driver 版本从 367.57 更新到 375.20
* CentOS 默认 yum repo 源从 bootstrapper 改为  mirrors.aliyun.com
* sample 中 Ceph 改为默认关闭，不安装配置
> Fix bugs in test

- scripts/common.sh
主要改动两点：
1. 把证书的默认有效期从 365 天改为 3650 天
2. 把每次运行 bsroot.sh 重新生成证书的逻辑改为，如果证书文件不存在就重新生成，历史生成证书已经存在就使用目前现有的证书，主要是为了解决：https://github.com/k8sp/sextant/issues/491#issuecomment-277587784 的第一种做法
> Reserve TLS
